
services:
  mongo:
    image: mongo:6.0
    container_name: eventify-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: Abdellatif
      MONGO_INITDB_ROOT_PASSWORD: abdo2010
      MONGO_INITDB_DATABASE: eventify
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    container_name: eventify-app
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://Abdellatif:abdo2010@mongo:27017/eventify

volumes:
  mongo-data:
